name: Build & Release All Home Packages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create zips for all design packages
        run: |
          mkdir -p output
          for dir in Design_Packages/*/; do
            pkg=$(basename "$dir")
            echo "Zipping $pkg..."
            zip -r "output/${pkg}.zip" "$dir"
          done

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Design_Packages_All
          path: output/*.zip

