    - name: Create or Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Home Packages
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Master Catalog
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: |
          Master_Catalog.zip
          Design_Packages/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

