name: Build & Release Home Package

on:
  push:
    paths:
      - 'Design_Packages/**'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pillow pandas openpyxl

      - name: Package new designs
        run: |
          for d in Design_Packages/*; do
            if [ -d "$d" ]; then
              pkg=$(basename "$d")
              zip -r "${pkg}.zip" "$d"
              mkdir -p thumbnails
              for img in "$d"/3D_Renders/*.png; do
                [ -f "$img" ] || continue
                thumb="thumbnails/${pkg}_$(basename "$img")"
                python3 - <<EOF
from PIL import Image, ImageDraw, ImageFont
img = Image.open("$img")
img.thumbnail((400, 400))
draw = ImageDraw.Draw(img)
draw.text((10,10), "MiMi & Son LLC K-Cribs", fill="white")
img.save("$thumb")
EOF
              done
            fi
          done

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
